name: Read Google Sheet

on:
  workflow_dispatch:

jobs:
  read-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # get repo code [web:12]
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # any supported version is fine [web:12]

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas
        # gspread provides helpers for service-account auth [web:95]

      # Pattern A: base64 secret -> file
      - name: Write Google creds to file
        if: env.USE_FILE == '1'
        run: |
          echo "$GOOGLE_CREDS_B64" | base64 -d > google-creds.json
          ls -l google-creds.json
        env:
          GOOGLE_CREDS_B64: ${{ secrets.GOOGLE_CREDS_B64 }}
          USE_FILE: '1'
        # Writing secrets to files in workflows is a common approach [web:107][web:111]

      - name: Run script (file path)
        if: env.USE_FILE == '1'
        env:
          GOOGLE_CREDS: google-creds.json
        run: python your_script.py
        # Script reads GOOGLE_CREDS path and authenticates [web:12]

      # Pattern B: pass raw JSON dict via env
      - name: Run script (dict auth)
        if: env.USE_FILE != '1'
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: python your_script.py
        # Script parses GOOGLE_CREDS_JSON and authenticates via dict [web:95][web:101]
